# ==============================
# CSV to DAT Converter
# ==============================
#
# This script converts a .csv file to .dat file from the synthetic student preferences generator
# compatible with the course allocation optimization model.
# input_csv -> file generated by the script syntheticStudentGenerator.py with the preferences of the students
# courses_csv -> informations about the courses
# parametres_json -> general informations about the AI and CS formations
#
# Usage:
#   python convertisseur.py [--input studentsRandom.csv] [--courses coursesS1.csv] [--params parameters.json] [--out students.dat]

import argparse
import csv
import json


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert student preferences CSV to OPL .dat file."
    )
    parser.add_argument(
        "--input", type=str, default="studentsRandom.csv", help="Students CSV file"
    )
    parser.add_argument(
        "--courses", type=str, default="coursesS1_old.csv", help="Courses CSV file"
    )
    parser.add_argument(
        "--params", type=str, default="parameters.json", help="Parameters JSON file"
    )
    parser.add_argument(
        "--out", type=str, default="students.dat", help="Output .dat file"
    )
    return parser.parse_args()


def read_students(input_csv):
    students = []
    # mmax = []
    maxOptional = []
    parc = []
    r = []

    with open(input_csv, newline="") as f:
        reader = csv.DictReader(f)

        rg_cols = [col for col in reader.fieldnames if col.startswith("Rg")]
        m = len(rg_cols)

        for row in reader:
            students.append(int(row["studentID"]))

            maxOptional.append(int(row["maxOptional"]))

            if row["CS_track"] == "true":
                parc.append(1)
            elif row["AI_track"] == "true":
                parc.append(2)

            ranks = [float(row[col]) for col in rg_cols]
            r.append(ranks)

    n = len(students)
    return students, maxOptional, parc, r, n, m


def read_courses(courses_csv, n):
    mandatory = set()
    mandIA = 0
    mandCS = 0

    # Pas de conflits EDT pour l'instant -> ensemble vide
    # Si des conflits existent -> conflicts.add((ue1, ue2)) ue1 < ue2
    conflicts = set()
    c = []

    with open(courses_csv, newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            course_id = int(row["courseID"]) - 1

            spots = int(row["spots"])
            if spots == -1:  # number of places unlimited -> number of students places
                spots = n

            c.append(spots)

            if row["CS_track"] == "true":
                mandatory.add((course_id + 1, 1))
                mandCS += 1

            if row["AI_track"] == "true":
                mandatory.add((course_id + 1, 2))
                mandIA += 1

    return c, conflicts, mandatory, mandCS, mandIA


def compute_mmax(parc, maxOptional, mandCS, mandIA):
    mmax = []
    for i in range(len(parc)):
        if parc[i] == 1:  # CS
            mmax.append(maxOptional[i] + mandCS)  # mandatories + optionals courses
        else:  # IA
            mmax.append(maxOptional[i] + mandIA)
    return mmax


def read_params(parametres_json):
    with open(parametres_json) as f:
        params = json.load(f)

        mmin = [params["spe"]["CS_track"]["minNj"], params["spe"]["AI_track"]["minNj"]]

        gmin = params["spe"]["CS_track"]["minNj"]  # CS
        gmax = params["spe"]["CS_track"]["maxNj"]

        # gminAI = params["spe"]["AI_track"]["minNj"]  # AI
        # gmaxAI = params["spe"]["AI_track"]["maxNj"]

        objType = 1

    return mmin, gmin, gmax, objType


def write_dat(
    output_dat,
    n,
    m,
    p,
    gmin,
    gmax,
    objType,
    c,
    conflicts,
    mmin,
    mandatory,
    mmax,
    parc,
    r,
):
    with open(output_dat, "w") as f:
        f.write(
            "// ---------------------------------------------------------------------------\n"
        )
        f.write("// Dimensions\n")
        f.write(
            "// ---------------------------------------------------------------------------\n"
        )

        f.write(f"n = {n};  // Nombre d'étudiants\n")
        f.write(f"m = {m};  // Nombre d'UE\n")
        f.write(f"p = {p};  // Nombre de parcours (1=Informatique, 2=IA)\n\n")

        f.write(f"gmin = {gmin};  // Minimum d'UE a suivre (toutes UE confondues)\n")
        f.write(f"gmax = {gmax};  // Maximum d'UE a suivre (toutes UE confondues)\n")
        f.write(f"objType = {objType};  // 1 = somme des rangs, 2 = pire rang\n\n")

        f.write(
            "// ---------------------------------------------------------------------------\n"
        )
        f.write("// Cours\n")
        f.write(
            "// ---------------------------------------------------------------------------\n"
        )

        f.write("// c[j] : capacité (nombre de places disponibles) pour l'UE j\n ")
        f.write("c = [")
        f.write(", ".join(map(str, c)))
        f.write("];\n\n")

        # conflicts : ensemble de tuples <ue1, ue2> avec ue1 < ue2
        # Format OPL : conflicts = {<1,3>, <2,5>};  ou  conflicts = {};
        f.write("// conflicts : paires d'UE en conflit d'emploi du temps\n")
        f.write("conflicts = {")
        f.write(", ".join(f"<{u},{v}>" for u, v in sorted(conflicts)))
        f.write("};\n\n")

        f.write(
            "// ---------------------------------------------------------------------------\n"
        )
        f.write("// Parcours\n")
        f.write(
            "// ---------------------------------------------------------------------------\n"
        )

        f.write(
            "// mmin[k] : nombre minimum d'UE optionnelles à suivre dans le parcours k\n"
        )
        f.write("mmin = [")
        f.write(", ".join(map(str, mmin)))
        f.write("];\n\n")

        # mandatory : ensemble de tuples <ue, parcours>
        # Format OPL : mandatory = {<2,1>, <3,1>, <5,2>};
        f.write("// mandatory : paires (UE obligatoire, parcours)\n")
        f.write("mandatory = {")
        f.write(", ".join(f"<{u},{k}>" for u, k in sorted(mandatory)))
        f.write("};\n\n")

        f.write(
            "// ---------------------------------------------------------------------------\n"
        )
        f.write("// Étudiants\n")
        f.write(
            "// ---------------------------------------------------------------------------\n"
        )

        f.write("// mmax[i] : nombre maximum d'UE souhaité par l'étudiant i\n")
        f.write("mmax = [")
        f.write(", ".join(map(str, mmax)))
        f.write("];\n\n")

        f.write("// parc[i] : parcours de l'étudiant i (1=Informatique, 2=IA)\n")
        f.write("parc = [")
        f.write(", ".join(map(str, parc)))
        f.write("];\n\n")

        f.write("// r[i][j] : rang de l'UE j pour l'étudiant i\n")
        f.write("r = [\n")
        for row in r:
            f.write("  [")
            f.write(", ".join(map(str, row)))
            f.write("],\n")
        f.write("];\n")


def main():
    args = parse_args()

    p = 2

    students, maxOptional, parc, r, n, m = read_students(args.input)
    c, conflicts, mandatory, mandCS, mandIA = read_courses(args.courses, n)
    mmax = compute_mmax(parc, maxOptional, mandCS, mandIA)
    mmin, gmin, gmax, objType = read_params(args.params)

    write_dat(
        args.out,
        n,
        m,
        p,
        gmin,
        gmax,
        objType,
        c,
        conflicts,
        mmin,
        mandatory,
        mmax,
        parc,
        r,
    )

    print("Fichier .dat généré :", args.out)


if __name__ == "__main__":
    main()
