# ==============================
# CSV to DAT Converter
# ==============================
#
# This script converts a .csv file to .dat file from the synthetic strudent preferences generator
# compatible with the course allocation optimization model.
# input_csv -> file generated by the script syntheticStudentGenerator.py with the preferences of the students
# courses_csv -> informations about the courses
# parametres_json -> general informations about the AI and CS formations
import csv
import json

input_csv = "studentsRandom.csv"
courses_csv = "courses.csv"
parametres_json = "parameters.json"
output_dat = "students.dat"

students = []
mmax = []
maxOptional = []  # on stocke les options ici
parc = []
r = []
c = []

# -------------------------
# STUDENTS
# -------------------------

with open(input_csv, newline="") as f:
    reader = csv.DictReader(f)

    rg_cols = [col for col in reader.fieldnames if col.startswith("Rg")]
    m = len(rg_cols)

    for row in reader:
        students.append(int(row["studentID"]))

        maxOptional.append(int(row["maxOptional"]))

        if row["CS_track"] == "true":
            parc.append(1)
        elif row["AI_track"] == "true":
            parc.append(2)

        ranks = [float(row[col]) for col in rg_cols]
        r.append(ranks)

n = len(students)
p = 2

# -------------------------
# COURSES
# -------------------------

mand = [[0 for _ in range(p)] for _ in range(m)]

mandIA = 0
mandCS = 0

with open(courses_csv, newline="") as f:
    reader = csv.DictReader(f)

    for row in reader:
        course_id = int(row["courseID"]) - 1

        spots = int(row["spots"])
        if spots == -1:  # number of places illimated -> number of students places
            spots = n

        c.append(spots)

        if row["CS_track"] == "true":
            mand[course_id][0] = 1
            mandCS += 1

        if row["AI_track"] == "true":
            mand[course_id][1] = 1
            mandIA += 1

# print("Mandatories IA:", mandIA, "Mandatories CS:", mandCS)
for i in range(n):
    if parc[i] == 1:  # CS
        mmax.append(maxOptional[i] + mandCS)  # mandatories + optionals courses
    else:  # IA
        mmax.append(maxOptional[i] + mandIA)

# pour le moment nous n'avons pas mis les contraintes d'EDT, on initialise donc la matrice à vide
Ic = [[0 for _ in range(m)] for _ in range(m)]

with open(parametres_json) as f:
    params = json.load(f)

    mmin = [params["spe"]["CS_track"]["minNj"], params["spe"]["AI_track"]["minNj"]]

# -------------------------
# WRITE DAT in the .dat file
# -------------------------

with open(output_dat, "w") as f:
    f.write(
        "// ---------------------------------------------------------------------------\n"
    )
    f.write("// Dimensions\n")
    f.write(
        "// ---------------------------------------------------------------------------\n"
    )

    f.write(f"n = {n};  // Nombre d'étudiants\n")
    f.write(f"m = {m};  // Nombre d'UE\n")
    f.write(f"p = {p};  // Nombre de parcours (1=Informatique, 2=IA)\n\n")

    f.write(
        "// ---------------------------------------------------------------------------\n"
    )
    f.write("// Cours\n")
    f.write(
        "// ---------------------------------------------------------------------------\n"
    )

    f.write("// c[j] : capacité (nombre de places disponibles) pour l'UE j\n ")
    f.write("c = [")
    f.write(", ".join(map(str, c)))
    f.write("];\n\n")

    f.write("// Ic[j][j2] : 1 si les UE j et j2 sont en conflit d'emploi du temps\n")
    f.write("Ic = [\n")
    for row in Ic:
        f.write("  [")
        f.write(", ".join(map(str, row)))
        f.write("],\n")
    f.write("];\n\n")

    f.write(
        "// ---------------------------------------------------------------------------\n"
    )
    f.write("// Parcours\n")
    f.write(
        "// ---------------------------------------------------------------------------\n"
    )

    f.write(
        "// mmin[k] : nombre minimum d'UE optionnelles à suivre dans le parcours k\n"
    )
    f.write("mmin = [")
    f.write(", ".join(map(str, mmin)))
    f.write("];\n\n")

    f.write("// mand[j][k] : 1 si l'UE j est obligatoire dans le parcours k\n")
    f.write("mand = [\n")
    for row in mand:
        f.write("  [")
        f.write(", ".join(map(str, row)))
        f.write("],\n")
    f.write("];\n\n")

    f.write(
        "// ---------------------------------------------------------------------------\n"
    )
    f.write("// Étudiants\n")
    f.write(
        "// ---------------------------------------------------------------------------\n"
    )

    f.write("// mmax[i] : nombre maximum d'UE souhaité par l'étudiant i\n")
    f.write("mmax = [")
    f.write(", ".join(map(str, mmax)))
    f.write("];\n\n")

    f.write("// parc[i] : parcours de l'étudiant i (1=Informatique, 2=IA)\n")
    f.write("parc = [")
    f.write(", ".join(map(str, parc)))
    f.write("];\n\n")

    f.write("// r[i][j] : rang de l'UE j pour l'étudiant i\n")
    f.write("r = [\n")
    for row in r:
        f.write("  [")
        f.write(", ".join(map(str, row)))
        f.write("],\n")
    f.write("];\n")


print("Fichier .dat généré :", output_dat)
