name: CI Basic

on:
  push:
    branches: [main, dev] # trigger on push to main and dev
  pull_request:
    branches: [main, dev] # trigger on pull request to main and dev
  workflow_dispatch: # allows manual trigger from GitHub UI

  schedule: # Schedule workflow to run at 6:00 UTC on Monday
    - cron: '0 6 * * 1'

# Permissions are needed to read privileged
permissions:
  contents: read
  # This permission is required when uploading sarifs to any repository at GitHub
  security-events: write
  # These permissions are only required when uploading sarifs to private and internal repositories at GitHub
  actions: read

# Annule les runs obsolètes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  # ================= Continuous Integration =================

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Harden the runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/setup-python@v5     # v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Harden the runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - uses: actions/setup-python@v5     # v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -v

  # ================= Security Gates =================
  # Gate 1 : Secrets (block immediately)
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Detect secrets
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Gate 2 : SAST (block sur critical / high)
  sast:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF file for Github Advanced Security
        uses: github/codeql-action/upload-sarif@ebcb5b36ded6beda4ceefea6a8bc4cc885255bb3 # v3
        with:
          sarif_file: semgrep.sarif
        if: always()
# Gate 3: SCA (Dependency Analysis)
  sca:
    name: 📦 SCA (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Harden the runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: audit

      - name: Run Trivy (SARIF)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v2.25.0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Fail on critical vulnerabilities
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  # Gate final : check if all previous gates passed
  security-pass:
    needs: [secrets, sast, sca]
    runs-on: ubuntu-latest
    if: always() #
    steps:
      - name: Check if all previous gates passed
        run: |
          for result in "${{ needs.secrets.result }}" "${{ needs.sast.result }}" "${{ needs.sca.result }}"; do
            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
              echo "One or more security gates failed: $result"
              exit 1
            fi
          done
          echo "All security gates passed"

# =========== Continuous Delivery  ==========
